import { randomUUID } from "node:crypto";
import { and, eq, inArray } from "drizzle-orm";
import { z } from "zod";
import type { BetterSQLite3Database } from "drizzle-orm/better-sqlite3";
import * as schema from "./schema";
import { accounts, eventFacts, scheduledEvents } from "./schema";
import {
  recurrenceSchema,
  transactionType,
} from "./types";
import type { FactLookup } from "@/lib/engines/forecast";

type DB = BetterSQLite3Database<typeof schema>;

export const createEventInput = z.object({
  title: z.string().min(1).max(120),
  baseAmount: z.number().int().nonnegative(),
  transactionType,
  accountId: z.string().uuid(),
  toAccountId: z.string().uuid().optional(),
  category: z.string().max(80).optional(),
  recurrence: recurrenceSchema,
  isActive: z.boolean().default(true),
  autoGenerated: z.boolean().default(false),
});

export type CreateEventInput = z.infer<typeof createEventInput>;

export async function insertEvent(
  db: DB,
  userId: string,
  rawInput: unknown,
): Promise<string> {
  const input = createEventInput.parse(rawInput);

  // validate referenced accounts belong to user
  const accountIds = [input.accountId, input.toAccountId].filter(
    (x): x is string => !!x,
  );
  const owned = await db
    .select({ id: accounts.id })
    .from(accounts)
    .where(and(eq(accounts.userId, userId), inArray(accounts.id, accountIds)));
  if (owned.length !== accountIds.length) {
    throw new Error("Referenced account not owned by user");
  }

  const id = randomUUID();
  await db.insert(scheduledEvents).values({
    id,
    userId,
    title: input.title,
    baseAmount: input.baseAmount,
    transactionType: input.transactionType,
    accountId: input.accountId,
    toAccountId: input.toAccountId ?? null,
    category: input.category ?? null,
    recurrence: input.recurrence,
    isActive: input.isActive,
    autoGenerated: input.autoGenerated,
    createdAt: new Date(),
  });
  return id;
}

export async function listEvents(db: DB, userId: string) {
  return db
    .select()
    .from(scheduledEvents)
    .where(eq(scheduledEvents.userId, userId));
}

export async function deleteEvent(db: DB, userId: string, id: string): Promise<void> {
  await db
    .delete(scheduledEvents)
    .where(and(eq(scheduledEvents.userId, userId), eq(scheduledEvents.id, id)));
}

export async function toggleEventActive(
  db: DB,
  userId: string,
  id: string,
  isActive: boolean,
): Promise<void> {
  await db
    .update(scheduledEvents)
    .set({ isActive })
    .where(and(eq(scheduledEvents.userId, userId), eq(scheduledEvents.id, id)));
}

export async function loadFactLookup(
  db: DB,
  userId: string,
  eventIds: string[],
): Promise<FactLookup> {
  const lookup: FactLookup = new Map();
  if (eventIds.length === 0) return lookup;
  const rows = await db
    .select()
    .from(eventFacts)
    .where(
      and(
        eq(eventFacts.userId, userId),
        inArray(eventFacts.eventId, eventIds),
      ),
    );
  for (const row of rows) {
    const inner =
      lookup.get(row.eventId) ?? new Map<string, { status: typeof row.status; actualAmount: number }>();
    inner.set(row.monthKey, {
      status: row.status,
      actualAmount: row.actualAmount,
    });
    lookup.set(row.eventId, inner);
  }
  return lookup;
}

import { startOfDay, subMonths } from "date-fns";
import { expandRecurrence } from "@/lib/engines/forecast";

export type OverdueEntry = {
  eventId: string;
  title: string;
  baseAmount: number;
  transactionType: import("./types").TransactionType;
  accountId: string;
  toAccountId: string | null;
  plannedDateMs: number;
  monthKey: string; // YYYY-MM of plannedDate
};

const monthKey = (d: Date): string =>
  `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;

/**
 * Returns scheduled-event occurrences whose planned date is in the past
 * (yesterday or earlier) AND have no recorded fact for that month.
 *
 * Look-back window defaults to 6 months. Only `once` and `monthlyByDay`
 * recurrences are considered (weekly facts would require a different
 * unique key in event_facts).
 */
export async function findOverdueEvents(
  db: DB,
  userId: string,
  today: Date,
  monthsBack = 6,
): Promise<OverdueEntry[]> {
  const allEvents = await db
    .select()
    .from(scheduledEvents)
    .where(eq(scheduledEvents.userId, userId));

  const activeUserEvents = allEvents.filter(
    (e) => e.isActive && !e.autoGenerated,
  );
  if (activeUserEvents.length === 0) return [];

  const facts = await loadFactLookup(
    db,
    userId,
    activeUserEvents.map((e) => e.id),
  );

  const todayStart = startOfDay(today);
  const floor = subMonths(todayStart, monthsBack);
  const horizon = new Date(todayStart.getTime() - 86_400_000); // yesterday inclusive

  const out: OverdueEntry[] = [];
  for (const ev of activeUserEvents) {
    if (
      ev.recurrence.kind !== "once" &&
      ev.recurrence.kind !== "monthlyByDay"
    ) {
      continue;
    }
    const occurrences = expandRecurrence(ev.recurrence, floor, horizon);
    for (const d of occurrences) {
      const k = monthKey(d);
      const fact = facts.get(ev.id)?.get(k);
      if (fact) continue; // already resolved (fact or skipped)
      out.push({
        eventId: ev.id,
        title: ev.title,
        baseAmount: ev.baseAmount,
        transactionType: ev.transactionType,
        accountId: ev.accountId,
        toAccountId: ev.toAccountId ?? null,
        plannedDateMs: d.getTime(),
        monthKey: k,
      });
    }
  }
  // newest overdue first
  out.sort((a, b) => b.plannedDateMs - a.plannedDateMs);
  return out;
}

/**
 * Mark an event occurrence as a fact (with actual amount/date) or skipped.
 * If `linkTransactionId` is provided, links the event_facts row to that
 * transaction so the day-level state stays consistent.
 */
export async function upsertEventFact(
  db: DB,
  userId: string,
  input: {
    eventId: string;
    monthKey: string;
    status: "fact" | "skipped";
    actualAmount: number;
    actualDateMs: number;
    transactionId?: string | null;
  },
): Promise<void> {
  const exists = await db
    .select({ id: eventFacts.id })
    .from(scheduledEvents)
    .innerJoin(eventFacts, eq(eventFacts.eventId, scheduledEvents.id))
    .where(
      and(
        eq(scheduledEvents.userId, userId),
        eq(scheduledEvents.id, input.eventId),
        eq(eventFacts.monthKey, input.monthKey),
      ),
    );
  if (exists.length > 0) {
    await db
      .update(eventFacts)
      .set({
        status: input.status,
        actualAmount: input.actualAmount,
        actualDate: new Date(input.actualDateMs),
        transactionId: input.transactionId ?? null,
      })
      .where(
        and(
          eq(eventFacts.eventId, input.eventId),
          eq(eventFacts.monthKey, input.monthKey),
        ),
      );
    return;
  }
  // verify ownership
  const owns = await db
    .select({ id: scheduledEvents.id })
    .from(scheduledEvents)
    .where(
      and(
        eq(scheduledEvents.userId, userId),
        eq(scheduledEvents.id, input.eventId),
      ),
    );
  if (owns.length === 0) throw new Error("Событие не принадлежит пользователю");
  await db.insert(eventFacts).values({
    id: randomUUID(),
    userId,
    eventId: input.eventId,
    monthKey: input.monthKey,
    status: input.status,
    actualAmount: input.actualAmount,
    actualDate: new Date(input.actualDateMs),
    transactionId: input.transactionId ?? null,
    createdAt: new Date(),
  });
}
