import { randomUUID } from "node:crypto";
import { and, eq, inArray } from "drizzle-orm";
import { z } from "zod";
import type { BetterSQLite3Database } from "drizzle-orm/better-sqlite3";
import * as schema from "./schema";
import { accounts, eventFacts, scheduledEvents } from "./schema";
import {
  recurrenceSchema,
  transactionType,
} from "./types";
import type { FactLookup } from "@/lib/engines/forecast";

type DB = BetterSQLite3Database<typeof schema>;

export const createEventInput = z.object({
  title: z.string().min(1).max(120),
  baseAmount: z.number().int().nonnegative(),
  transactionType,
  accountId: z.string().uuid(),
  toAccountId: z.string().uuid().optional(),
  category: z.string().max(80).optional(),
  recurrence: recurrenceSchema,
  isActive: z.boolean().default(true),
  autoGenerated: z.boolean().default(false),
});

export type CreateEventInput = z.infer<typeof createEventInput>;

export async function insertEvent(
  db: DB,
  userId: string,
  rawInput: unknown,
): Promise<string> {
  const input = createEventInput.parse(rawInput);

  // validate referenced accounts belong to user
  const accountIds = [input.accountId, input.toAccountId].filter(
    (x): x is string => !!x,
  );
  const owned = await db
    .select({ id: accounts.id })
    .from(accounts)
    .where(and(eq(accounts.userId, userId), inArray(accounts.id, accountIds)));
  if (owned.length !== accountIds.length) {
    throw new Error("Referenced account not owned by user");
  }

  const id = randomUUID();
  await db.insert(scheduledEvents).values({
    id,
    userId,
    title: input.title,
    baseAmount: input.baseAmount,
    transactionType: input.transactionType,
    accountId: input.accountId,
    toAccountId: input.toAccountId ?? null,
    category: input.category ?? null,
    recurrence: input.recurrence,
    isActive: input.isActive,
    autoGenerated: input.autoGenerated,
    createdAt: new Date(),
  });
  return id;
}

export async function listEvents(db: DB, userId: string) {
  return db
    .select()
    .from(scheduledEvents)
    .where(eq(scheduledEvents.userId, userId));
}

export async function deleteEvent(db: DB, userId: string, id: string): Promise<void> {
  await db
    .delete(scheduledEvents)
    .where(and(eq(scheduledEvents.userId, userId), eq(scheduledEvents.id, id)));
}

export async function toggleEventActive(
  db: DB,
  userId: string,
  id: string,
  isActive: boolean,
): Promise<void> {
  await db
    .update(scheduledEvents)
    .set({ isActive })
    .where(and(eq(scheduledEvents.userId, userId), eq(scheduledEvents.id, id)));
}

export async function loadFactLookup(
  db: DB,
  userId: string,
  eventIds: string[],
): Promise<FactLookup> {
  const lookup: FactLookup = new Map();
  if (eventIds.length === 0) return lookup;
  const rows = await db
    .select()
    .from(eventFacts)
    .where(
      and(
        eq(eventFacts.userId, userId),
        inArray(eventFacts.eventId, eventIds),
      ),
    );
  for (const row of rows) {
    const inner =
      lookup.get(row.eventId) ?? new Map<string, { status: typeof row.status; actualAmount: number }>();
    inner.set(row.monthKey, {
      status: row.status,
      actualAmount: row.actualAmount,
    });
    lookup.set(row.eventId, inner);
  }
  return lookup;
}
