import { relations } from "drizzle-orm";
import {
  sqliteTable,
  text,
  integer,
  index,
  uniqueIndex,
  type AnySQLiteColumn,
} from "drizzle-orm/sqlite-core";
import type {
  AccountType,
  CreditCardSettings,
  EventStatus,
  LoanSettings,
  Recurrence,
  TransactionType,
} from "./types";

export const users = sqliteTable("users", {
  id: text("id").primaryKey(),
  email: text("email").notNull().unique(),
  name: text("name").notNull(),
  passwordHash: text("password_hash").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
});

export const accounts = sqliteTable(
  "accounts",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    type: text("type").$type<AccountType>().notNull(),
    name: text("name").notNull(),
    balance: integer("balance").notNull(),
    interestRate: text("interest_rate"),
    interestPayoutDay: integer("interest_payout_day"),
    creditCardSettings: text("credit_card_settings", {
      mode: "json",
    }).$type<CreditCardSettings>(),
    loanSettings: text("loan_settings", {
      mode: "json",
    }).$type<LoanSettings>(),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  },
  (t) => [
    index("accounts_user_idx").on(t.userId),
    index("accounts_user_type_idx").on(t.userId, t.type),
  ],
);

export const scheduledEvents = sqliteTable(
  "scheduled_events",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    title: text("title").notNull(),
    baseAmount: integer("base_amount").notNull(),
    transactionType: text("transaction_type").$type<TransactionType>().notNull(),
    accountId: text("account_id")
      .notNull()
      .references(() => accounts.id, { onDelete: "cascade" }),
    toAccountId: text("to_account_id").references(
      (): AnySQLiteColumn => accounts.id,
      { onDelete: "cascade" },
    ),
    category: text("category"),
    recurrence: text("recurrence", { mode: "json" })
      .$type<Recurrence>()
      .notNull(),
    isActive: integer("is_active", { mode: "boolean" }).notNull().default(true),
    autoGenerated: integer("auto_generated", { mode: "boolean" })
      .notNull()
      .default(false),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  },
  (t) => [
    index("events_user_idx").on(t.userId),
    index("events_user_account_idx").on(t.userId, t.accountId),
  ],
);

export const transactions = sqliteTable(
  "transactions",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    type: text("type").$type<TransactionType>().notNull(),
    amount: integer("amount").notNull(),
    date: integer("date", { mode: "timestamp_ms" }).notNull(),
    title: text("title").notNull(),
    category: text("category"),
    note: text("note"),
    accountId: text("account_id").references(() => accounts.id, {
      onDelete: "cascade",
    }),
    fromAccountId: text("from_account_id").references(
      (): AnySQLiteColumn => accounts.id,
      { onDelete: "cascade" },
    ),
    toAccountId: text("to_account_id").references(
      (): AnySQLiteColumn => accounts.id,
      { onDelete: "cascade" },
    ),
    scheduledEventId: text("scheduled_event_id").references(
      () => scheduledEvents.id,
      { onDelete: "set null" },
    ),
    principalPart: integer("principal_part"),
    interestPart: integer("interest_part"),
    extraPayment: integer("extra_payment"),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  },
  (t) => [
    index("tx_user_date_idx").on(t.userId, t.date),
    index("tx_user_account_idx").on(t.userId, t.accountId),
    index("tx_user_from_idx").on(t.userId, t.fromAccountId),
    index("tx_user_to_idx").on(t.userId, t.toAccountId),
    index("tx_event_idx").on(t.scheduledEventId),
  ],
);

export const eventFacts = sqliteTable(
  "event_facts",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    eventId: text("event_id")
      .notNull()
      .references(() => scheduledEvents.id, { onDelete: "cascade" }),
    monthKey: text("month_key").notNull(),
    actualAmount: integer("actual_amount").notNull(),
    actualDate: integer("actual_date", { mode: "timestamp_ms" }).notNull(),
    status: text("status").$type<EventStatus>().notNull(),
    transactionId: text("transaction_id").references(() => transactions.id, {
      onDelete: "set null",
    }),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  },
  (t) => [
    uniqueIndex("event_facts_event_month_uq").on(t.eventId, t.monthKey),
    index("event_facts_user_month_idx").on(t.userId, t.monthKey),
  ],
);

export const usersRelations = relations(users, ({ many }) => ({
  accounts: many(accounts),
  transactions: many(transactions),
  events: many(scheduledEvents),
  eventFacts: many(eventFacts),
}));

export const accountsRelations = relations(accounts, ({ one, many }) => ({
  user: one(users, { fields: [accounts.userId], references: [users.id] }),
  transactionsOwned: many(transactions, { relationName: "tx_account" }),
  transfersOut: many(transactions, { relationName: "tx_from" }),
  transfersIn: many(transactions, { relationName: "tx_to" }),
  scheduledFrom: many(scheduledEvents, { relationName: "event_from" }),
  scheduledTo: many(scheduledEvents, { relationName: "event_to" }),
}));

export const scheduledEventsRelations = relations(
  scheduledEvents,
  ({ one, many }) => ({
    user: one(users, {
      fields: [scheduledEvents.userId],
      references: [users.id],
    }),
    account: one(accounts, {
      fields: [scheduledEvents.accountId],
      references: [accounts.id],
      relationName: "event_from",
    }),
    toAccount: one(accounts, {
      fields: [scheduledEvents.toAccountId],
      references: [accounts.id],
      relationName: "event_to",
    }),
    facts: many(eventFacts),
    transactions: many(transactions),
  }),
);

export const transactionsRelations = relations(transactions, ({ one }) => ({
  user: one(users, { fields: [transactions.userId], references: [users.id] }),
  account: one(accounts, {
    fields: [transactions.accountId],
    references: [accounts.id],
    relationName: "tx_account",
  }),
  fromAccount: one(accounts, {
    fields: [transactions.fromAccountId],
    references: [accounts.id],
    relationName: "tx_from",
  }),
  toAccount: one(accounts, {
    fields: [transactions.toAccountId],
    references: [accounts.id],
    relationName: "tx_to",
  }),
  scheduledEvent: one(scheduledEvents, {
    fields: [transactions.scheduledEventId],
    references: [scheduledEvents.id],
  }),
}));

export const eventFactsRelations = relations(eventFacts, ({ one }) => ({
  user: one(users, { fields: [eventFacts.userId], references: [users.id] }),
  event: one(scheduledEvents, {
    fields: [eventFacts.eventId],
    references: [scheduledEvents.id],
  }),
  transaction: one(transactions, {
    fields: [eventFacts.transactionId],
    references: [transactions.id],
  }),
}));

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type Account = typeof accounts.$inferSelect;
export type NewAccount = typeof accounts.$inferInsert;
export type Transaction = typeof transactions.$inferSelect;
export type NewTransaction = typeof transactions.$inferInsert;
export type ScheduledEvent = typeof scheduledEvents.$inferSelect;
export type NewScheduledEvent = typeof scheduledEvents.$inferInsert;
export type EventFact = typeof eventFacts.$inferSelect;
export type NewEventFact = typeof eventFacts.$inferInsert;
