import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { randomUUID } from "node:crypto";
import { eq } from "drizzle-orm";
import {
  accounts,
  eventFacts,
  scheduledEvents,
  transactions,
  users,
} from "@/lib/db/schema";
import {
  creditCardSettingsSchema,
  loanSettingsSchema,
  recurrenceSchema,
} from "@/lib/db/types";
import { createTestDb, type TestDB } from "./helpers/test-db";

let harness: ReturnType<typeof createTestDb>;
let db: TestDB;
let userId: string;

beforeEach(async () => {
  harness = createTestDb();
  db = harness.db;
  userId = randomUUID();
  await db.insert(users).values({
    id: userId,
    email: "a@b.test",
    name: "Test",
    passwordHash: "hash",
    createdAt: new Date(),
  });
});

afterEach(() => {
  harness.close();
});

describe("accounts schema", () => {
  it("round-trips creditCardSettings JSON", async () => {
    const settings = creditCardSettingsSchema.parse({
      creditLimit: 10_000_000,
      statementDay: 26,
      paymentDueDay: 19,
      annualRate: "0.599",
      minPaymentRate: "0.08",
      minPaymentFloor: 60_000,
      statementDebt: 2_650_000,
      lastStatementDate: Date.UTC(2026, 2, 26),
      paidAfterStatement: 0,
    });

    const id = randomUUID();
    await db.insert(accounts).values({
      id,
      userId,
      type: "creditCard",
      name: "Кредитка",
      balance: 2_650_000,
      creditCardSettings: settings,
      createdAt: new Date(),
    });

    const [row] = await db.select().from(accounts).where(eq(accounts.id, id));
    expect(row.creditCardSettings).toEqual(settings);
    expect(row.type).toBe("creditCard");
  });

  it("round-trips loanSettings JSON", async () => {
    const settings = loanSettingsSchema.parse({
      principal: 35_000_000,
      annualRate: "0.365",
      basePayment: 1_284_000,
      paymentDay: 1,
      startDate: Date.UTC(2026, 2, 15),
      originalTerm: 59,
      remainingTerm: 58,
      paidThisMonth: true,
      lastPaymentDate: Date.UTC(2026, 3, 1),
    });

    const id = randomUUID();
    await db.insert(accounts).values({
      id,
      userId,
      type: "loan",
      name: "Кредит",
      balance: 34_015_000,
      loanSettings: settings,
      createdAt: new Date(),
    });

    const [row] = await db.select().from(accounts).where(eq(accounts.id, id));
    expect(row.loanSettings).toEqual(settings);
  });

  it("enforces user_id FK on accounts", async () => {
    await expect(
      db.insert(accounts).values({
        id: randomUUID(),
        userId: "does-not-exist",
        type: "debit",
        name: "x",
        balance: 0,
        createdAt: new Date(),
      }),
    ).rejects.toThrow(/FOREIGN KEY/i);
  });
});

describe("scheduled events + facts", () => {
  it("round-trips recurrence JSON and enforces unique (event,month)", async () => {
    const accountId = randomUUID();
    await db.insert(accounts).values({
      id: accountId,
      userId,
      type: "debit",
      name: "Дебет",
      balance: 0,
      createdAt: new Date(),
    });

    const recurrence = recurrenceSchema.parse({
      kind: "monthlyByDay",
      day: 5,
    });
    const eventId = randomUUID();
    await db.insert(scheduledEvents).values({
      id: eventId,
      userId,
      title: "Зарплата",
      baseAmount: 4_600_000,
      transactionType: "income",
      accountId,
      recurrence,
      isActive: true,
      autoGenerated: false,
      createdAt: new Date(),
    });

    const [event] = await db
      .select()
      .from(scheduledEvents)
      .where(eq(scheduledEvents.id, eventId));
    expect(event.recurrence).toEqual(recurrence);
    expect(event.isActive).toBe(true);

    await db.insert(eventFacts).values({
      id: randomUUID(),
      userId,
      eventId,
      monthKey: "2026-04",
      actualAmount: 4_600_000,
      actualDate: new Date(),
      status: "fact",
      createdAt: new Date(),
    });

    await expect(
      db.insert(eventFacts).values({
        id: randomUUID(),
        userId,
        eventId,
        monthKey: "2026-04",
        actualAmount: 4_500_000,
        actualDate: new Date(),
        status: "fact",
        createdAt: new Date(),
      }),
    ).rejects.toThrow(/UNIQUE/i);
  });
});

describe("transactions", () => {
  it("cascades on user deletion and preserves set null on scheduled_event_id", async () => {
    const accountId = randomUUID();
    await db.insert(accounts).values({
      id: accountId,
      userId,
      type: "debit",
      name: "Дебет",
      balance: 0,
      createdAt: new Date(),
    });

    const eventId = randomUUID();
    await db.insert(scheduledEvents).values({
      id: eventId,
      userId,
      title: "Зарплата",
      baseAmount: 4_600_000,
      transactionType: "income",
      accountId,
      recurrence: { kind: "monthlyByDay", day: 5 },
      isActive: true,
      autoGenerated: false,
      createdAt: new Date(),
    });

    const txId = randomUUID();
    await db.insert(transactions).values({
      id: txId,
      userId,
      type: "income",
      amount: 4_600_000,
      date: new Date(),
      title: "Зарплата апрель",
      accountId,
      scheduledEventId: eventId,
      createdAt: new Date(),
    });

    await db.delete(scheduledEvents).where(eq(scheduledEvents.id, eventId));

    const [tx] = await db
      .select()
      .from(transactions)
      .where(eq(transactions.id, txId));
    expect(tx.scheduledEventId).toBeNull();

    await db.delete(users).where(eq(users.id, userId));
    const rows = await db
      .select()
      .from(transactions)
      .where(eq(transactions.id, txId));
    expect(rows).toHaveLength(0);
  });
});
