"use client";

import { useEffect, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Segmented } from "@/components/ui/segmented";
import { createEventAction } from "@/lib/actions/events";

type Account = { id: string; type: string; name: string };
type Kind = "expense" | "income";

function dateInputValue(d: Date): string {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

export function DayAddForm({
  defaultDate,
  accounts,
}: {
  defaultDate: Date;
  accounts: Account[];
}) {
  const router = useRouter();
  const [open, setOpen] = useState(false);
  const [isPending, startTransition] = useTransition();
  const [kind, setKind] = useState<Kind>("expense");
  const [title, setTitle] = useState("");
  const [amount, setAmount] = useState("");
  const [date, setDate] = useState(() => dateInputValue(defaultDate));
  const [accountId, setAccountId] = useState<string>(accounts[0]?.id ?? "");
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!open) setDate(dateInputValue(defaultDate));
  }, [defaultDate, open]);

  if (!open) {
    return (
      <Button
        variant="secondary"
        full
        onClick={() => setOpen(true)}
        className="mt-3"
      >
        <Plus size={16} />
        Добавить операцию
      </Button>
    );
  }

  function submit(e: React.FormEvent) {
    e.preventDefault();
    setError(null);
    const n = Number(amount.replace(",", "."));
    if (!Number.isFinite(n) || n <= 0) {
      setError("Введи сумму");
      return;
    }
    const ts = Date.parse(`${date}T12:00:00.000Z`);
    if (!Number.isFinite(ts)) {
      setError("Укажи дату");
      return;
    }
    if (!accountId) {
      setError("Выбери счёт");
      return;
    }
    const kopecks = Math.round(n * 100);
    startTransition(async () => {
      try {
        await createEventAction({
          title: title.trim() || (kind === "income" ? "Пополнение" : "Расход"),
          baseAmount: kopecks,
          transactionType: kind,
          accountId,
          recurrence: { kind: "once", date: ts },
          isActive: true,
          autoGenerated: false,
        });
        setOpen(false);
        setTitle("");
        setAmount("");
        router.refresh();
      } catch (err) {
        setError(err instanceof Error ? err.message : "Ошибка");
      }
    });
  }

  return (
    <Card className="mt-3">
      <form onSubmit={submit} className="flex flex-col gap-3">
        <Segmented<Kind>
          value={kind}
          onChange={setKind}
          options={[
            { value: "expense", label: "Расход" },
            { value: "income", label: "Пополнение" },
          ]}
        />
        <div className="flex flex-col gap-1.5">
          <Label htmlFor="day-evt-title">Название</Label>
          <Input
            id="day-evt-title"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            placeholder="Квартира, Зарплата…"
          />
        </div>
        <div className="grid grid-cols-2 gap-3">
          <div className="flex flex-col gap-1.5">
            <Label htmlFor="day-evt-amount">Сумма, ₽</Label>
            <Input
              id="day-evt-amount"
              type="number"
              step="0.01"
              value={amount}
              onChange={(e) => setAmount(e.target.value)}
              placeholder="0"
            />
          </div>
          <div className="flex flex-col gap-1.5">
            <Label htmlFor="day-evt-date">Дата</Label>
            <Input
              id="day-evt-date"
              type="date"
              value={date}
              onChange={(e) => setDate(e.target.value)}
            />
          </div>
        </div>
        <div className="flex flex-col gap-1.5">
          <Label htmlFor="day-evt-account">Счёт</Label>
          <select
            id="day-evt-account"
            value={accountId}
            onChange={(e) => setAccountId(e.target.value)}
            className="h-11 bg-surface border border-hairline rounded-[var(--radius)] px-3 text-sm outline-none focus:border-primary"
          >
            {accounts.map((a) => (
              <option key={a.id} value={a.id}>
                {a.name}
              </option>
            ))}
          </select>
        </div>
        {error && <div className="text-sm text-neg">{error}</div>}
        <div className="grid grid-cols-2 gap-2">
          <Button type="button" variant="ghost" full onClick={() => setOpen(false)}>
            Отмена
          </Button>
          <Button type="submit" full disabled={isPending}>
            {isPending ? "Сохраняем…" : "Сохранить"}
          </Button>
        </div>
      </form>
    </Card>
  );
}
