"use client";

import { useTransition } from "react";
import { Trash2 } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Chip } from "@/components/ui/chip";
import {
  deleteEventAction,
  toggleEventActiveAction,
} from "@/lib/actions/events";
import { formatRubles } from "@/lib/money";
import { cn } from "@/lib/utils";
import type { Recurrence, TransactionType } from "@/lib/db/types";

type EventItem = {
  id: string;
  title: string;
  baseAmount: number;
  transactionType: TransactionType;
  accountName: string;
  toAccountName?: string | null;
  recurrence: Recurrence;
  isActive: boolean;
  autoGenerated: boolean;
};

function describeRecurrence(r: Recurrence): string {
  switch (r.kind) {
    case "once":
      return `один раз ${new Date(r.date).toLocaleDateString("ru-RU")}`;
    case "monthlyByDay":
      return `каждое ${r.day}-е число`;
    case "weekly":
      return `еженедельно (${["пн", "вт", "ср", "чт", "пт", "сб", "вс"][r.weekday - 1]})`;
    case "custom":
      return "расписание";
  }
}

function describeType(t: TransactionType): string {
  return t === "income"
    ? "Доход"
    : t === "expense"
      ? "Расход"
      : t === "transfer"
        ? "Перевод"
        : t === "loanPayment"
          ? "Платёж по кредиту"
          : "Проценты";
}

export function EventList({ events }: { events: EventItem[] }) {
  const [isPending, startTransition] = useTransition();

  if (events.length === 0) {
    return (
      <div className="text-sm text-text-3 text-center py-12">
        Запланированных событий пока нет
      </div>
    );
  }

  return (
    <Card pad={false}>
      {events.map((e, i) => {
        const isIncome = e.transactionType === "income";
        return (
          <div
            key={e.id}
            className={cn(
              "px-[18px] py-4 flex items-start gap-3",
              i && "border-t border-hairline",
              !e.isActive && "opacity-50",
            )}
          >
            <div className="flex-1 min-w-0">
              <div className="flex items-center gap-2 mb-1">
                <div className="text-sm font-medium truncate">{e.title}</div>
                {e.autoGenerated && (
                  <Chip active={false}>AUTO</Chip>
                )}
              </div>
              <div className="text-xs text-text-3">
                {describeType(e.transactionType)} ·{" "}
                {describeRecurrence(e.recurrence)}
              </div>
              <div className="text-xs text-text-4 mt-1">
                {e.accountName}
                {e.toAccountName ? ` → ${e.toAccountName}` : ""}
              </div>
            </div>
            <div className="flex flex-col items-end gap-2 shrink-0">
              <div
                className={cn(
                  "tabular font-mono text-sm",
                  isIncome ? "text-pos" : "text-foreground",
                )}
              >
                {isIncome ? "+" : "−"}
                {formatRubles(e.baseAmount)}
              </div>
              <div className="flex items-center gap-1.5">
                <button
                  type="button"
                  onClick={() =>
                    startTransition(async () => {
                      await toggleEventActiveAction(e.id, !e.isActive);
                    })
                  }
                  disabled={isPending}
                  className={cn(
                    "text-[10px] label-mono px-2 h-6 rounded-full border transition-colors",
                    e.isActive
                      ? "border-pos text-pos"
                      : "border-hairline text-text-4",
                  )}
                >
                  {e.isActive ? "АКТИВНО" : "ВЫКЛ"}
                </button>
                {!e.autoGenerated && (
                  <button
                    type="button"
                    onClick={() =>
                      startTransition(async () => {
                        if (confirm(`Удалить «${e.title}»?`)) {
                          await deleteEventAction(e.id);
                        }
                      })
                    }
                    disabled={isPending}
                    className="size-6 flex items-center justify-center text-text-4 hover:text-neg transition-colors"
                    aria-label="Удалить"
                  >
                    <Trash2 size={14} />
                  </button>
                )}
              </div>
            </div>
          </div>
        );
      })}
    </Card>
  );
}
