"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Segmented } from "@/components/ui/segmented";
import { createEventAction } from "@/lib/actions/events";
import type { Recurrence } from "@/lib/db/types";

type Account = { id: string; type: string; name: string };
type Kind = "expense" | "income";

function defaultDateStr(): string {
  const d = new Date();
  d.setDate(d.getDate() + 7);
  return d.toISOString().slice(0, 10);
}

export function NewEventForm({ accounts }: { accounts: Account[] }) {
  const router = useRouter();
  const [open, setOpen] = useState(false);
  const [isPending, startTransition] = useTransition();
  const [kind, setKind] = useState<Kind>("expense");
  const [title, setTitle] = useState("");
  const [amount, setAmount] = useState("");
  const [recurring, setRecurring] = useState(false);
  const [date, setDate] = useState(defaultDateStr);
  const [day, setDay] = useState(1);
  const [accountId, setAccountId] = useState<string>(accounts[0]?.id ?? "");
  const [error, setError] = useState<string | null>(null);

  if (!open) {
    return (
      <Button
        variant="secondary"
        full
        onClick={() => setOpen(true)}
        className="mb-4"
      >
        <Plus size={16} />
        Новое событие
      </Button>
    );
  }

  function submit(e: React.FormEvent) {
    e.preventDefault();
    setError(null);
    const n = Number(amount.replace(",", "."));
    if (!Number.isFinite(n) || n <= 0) {
      setError("Введи сумму");
      return;
    }
    let recurrence: Recurrence;
    if (recurring) {
      if (day < 1 || day > 28) {
        setError("День месяца от 1 до 28");
        return;
      }
      recurrence = { kind: "monthlyByDay", day };
    } else {
      const ts = Date.parse(`${date}T12:00:00.000Z`);
      if (!Number.isFinite(ts)) {
        setError("Укажи дату");
        return;
      }
      recurrence = { kind: "once", date: ts };
    }
    const kopecks = Math.round(n * 100);
    startTransition(async () => {
      try {
        await createEventAction({
          title: title.trim() || (kind === "income" ? "Доход" : "Расход"),
          baseAmount: kopecks,
          transactionType: kind,
          accountId,
          recurrence,
          isActive: true,
          autoGenerated: false,
        });
        setOpen(false);
        setTitle("");
        setAmount("");
        setRecurring(false);
        setDate(defaultDateStr());
        setDay(1);
        router.refresh();
      } catch (err) {
        setError(err instanceof Error ? err.message : "Ошибка");
      }
    });
  }

  return (
    <Card className="mb-4">
      <form onSubmit={submit} className="flex flex-col gap-3">
        <Segmented<Kind>
          value={kind}
          onChange={setKind}
          options={[
            { value: "expense", label: "Расход" },
            { value: "income", label: "Доход" },
          ]}
        />
        <div className="flex flex-col gap-1.5">
          <Label htmlFor="evt-title">Название</Label>
          <Input
            id="evt-title"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            placeholder="Квартира, Подписка, Зарплата…"
          />
        </div>
        <div className="grid grid-cols-2 gap-3">
          <div className="flex flex-col gap-1.5">
            <Label htmlFor="evt-amount">Сумма, ₽</Label>
            <Input
              id="evt-amount"
              type="number"
              step="0.01"
              value={amount}
              onChange={(e) => setAmount(e.target.value)}
              placeholder="0"
            />
          </div>
          {recurring ? (
            <div className="flex flex-col gap-1.5">
              <Label htmlFor="evt-day">День месяца</Label>
              <Input
                id="evt-day"
                type="number"
                min={1}
                max={28}
                value={day}
                onChange={(e) => setDay(Number(e.target.value))}
              />
            </div>
          ) : (
            <div className="flex flex-col gap-1.5">
              <Label htmlFor="evt-date">Дата</Label>
              <Input
                id="evt-date"
                type="date"
                value={date}
                onChange={(e) => setDate(e.target.value)}
              />
            </div>
          )}
        </div>
        <label className="flex items-center gap-2 text-sm text-text-2 select-none cursor-pointer">
          <input
            type="checkbox"
            checked={recurring}
            onChange={(e) => setRecurring(e.target.checked)}
            className="size-4 rounded border-hairline bg-surface-2 accent-accent cursor-pointer"
          />
          Повторять ежемесячно
        </label>
        <div className="flex flex-col gap-1.5">
          <Label htmlFor="evt-account">Счёт</Label>
          <select
            id="evt-account"
            value={accountId}
            onChange={(e) => setAccountId(e.target.value)}
            className="h-11 bg-surface border border-hairline rounded-[var(--radius)] px-3 text-sm outline-none focus:border-primary"
          >
            {accounts.map((a) => (
              <option key={a.id} value={a.id}>
                {a.name}
              </option>
            ))}
          </select>
        </div>
        {error && <div className="text-sm text-neg">{error}</div>}
        <div className="flex gap-2">
          <Button type="button" variant="ghost" full onClick={() => setOpen(false)}>
            Отмена
          </Button>
          <Button type="submit" full disabled={isPending}>
            {isPending ? "Сохраняем…" : "Сохранить"}
          </Button>
        </div>
      </form>
    </Card>
  );
}
