"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Segmented } from "@/components/ui/segmented";
import { createEventAction } from "@/lib/actions/events";

type Account = { id: string; type: string; name: string };
type Kind = "expense" | "income";

export function NewEventForm({ accounts }: { accounts: Account[] }) {
  const router = useRouter();
  const [open, setOpen] = useState(false);
  const [isPending, startTransition] = useTransition();
  const [kind, setKind] = useState<Kind>("expense");
  const [title, setTitle] = useState("");
  const [amount, setAmount] = useState("");
  const [day, setDay] = useState(1);
  const [accountId, setAccountId] = useState<string>(accounts[0]?.id ?? "");
  const [error, setError] = useState<string | null>(null);

  if (!open) {
    return (
      <Button
        variant="secondary"
        full
        onClick={() => setOpen(true)}
        className="mb-4"
      >
        <Plus size={16} />
        Новое регулярное событие
      </Button>
    );
  }

  function submit(e: React.FormEvent) {
    e.preventDefault();
    setError(null);
    const n = Number(amount.replace(",", "."));
    if (!Number.isFinite(n) || n <= 0) {
      setError("Введи сумму");
      return;
    }
    const kopecks = Math.round(n * 100);
    startTransition(async () => {
      try {
        await createEventAction({
          title: title.trim() || (kind === "income" ? "Доход" : "Расход"),
          baseAmount: kopecks,
          transactionType: kind,
          accountId,
          recurrence: { kind: "monthlyByDay", day },
          isActive: true,
          autoGenerated: false,
        });
        setOpen(false);
        setTitle("");
        setAmount("");
        router.refresh();
      } catch (err) {
        setError(err instanceof Error ? err.message : "Ошибка");
      }
    });
  }

  return (
    <Card className="mb-4">
      <form onSubmit={submit} className="flex flex-col gap-3">
        <Segmented<Kind>
          value={kind}
          onChange={setKind}
          options={[
            { value: "expense", label: "Расход" },
            { value: "income", label: "Доход" },
          ]}
        />
        <div className="flex flex-col gap-1.5">
          <Label htmlFor="evt-title">Название</Label>
          <Input
            id="evt-title"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            placeholder="Квартира, Подписка, Зарплата…"
          />
        </div>
        <div className="grid grid-cols-2 gap-3">
          <div className="flex flex-col gap-1.5">
            <Label htmlFor="evt-amount">Сумма, ₽</Label>
            <Input
              id="evt-amount"
              type="number"
              step="0.01"
              value={amount}
              onChange={(e) => setAmount(e.target.value)}
              placeholder="0"
            />
          </div>
          <div className="flex flex-col gap-1.5">
            <Label htmlFor="evt-day">День месяца</Label>
            <Input
              id="evt-day"
              type="number"
              min={1}
              max={28}
              value={day}
              onChange={(e) => setDay(Number(e.target.value))}
            />
          </div>
        </div>
        <div className="flex flex-col gap-1.5">
          <Label htmlFor="evt-account">Счёт</Label>
          <select
            id="evt-account"
            value={accountId}
            onChange={(e) => setAccountId(e.target.value)}
            className="h-11 bg-surface border border-hairline rounded-[var(--radius)] px-3 text-sm outline-none focus:border-primary"
          >
            {accounts.map((a) => (
              <option key={a.id} value={a.id}>
                {a.name}
              </option>
            ))}
          </select>
        </div>
        {error && <div className="text-sm text-neg">{error}</div>}
        <div className="flex gap-2">
          <Button type="button" variant="ghost" full onClick={() => setOpen(false)}>
            Отмена
          </Button>
          <Button type="submit" full disabled={isPending}>
            {isPending ? "Сохраняем…" : "Сохранить"}
          </Button>
        </div>
      </form>
    </Card>
  );
}
