import { Header, BackLink } from "@/components/ui/header";
import { requireUser } from "@/lib/auth/session";
import { db } from "@/lib/db";
import { listAccounts } from "@/lib/db/accounts";
import { listEvents } from "@/lib/db/events";
import { CreditCardPayments } from "./credit-card-payments";
import { EventList } from "./event-list";
import { NewEventForm } from "./new-event-form";

export default async function EventsPage() {
  const user = await requireUser();
  const [accounts, events] = await Promise.all([
    listAccounts(db, user.id),
    listEvents(db, user.id),
  ]);
  const byId = new Map(accounts.map((a) => [a.id, a]));

  const items = events.map((e) => ({
    id: e.id,
    title: e.title,
    baseAmount: e.baseAmount,
    transactionType: e.transactionType,
    recurrence: e.recurrence,
    isActive: e.isActive,
    autoGenerated: e.autoGenerated,
    accountName: byId.get(e.accountId)?.name ?? "—",
    toAccountName: e.toAccountId ? byId.get(e.toAccountId)?.name ?? null : null,
  }));

  return (
    <>
      <Header title="Запланированные" left={<BackLink href="/profile" />} />
      <main className="flex-1 overflow-y-auto px-4 py-4">
        <CreditCardPayments accounts={accounts} />
        <NewEventForm
          accounts={accounts.map((a) => ({
            id: a.id,
            type: a.type,
            name: a.name,
          }))}
        />
        <EventList events={items} />
        <div className="h-6" />
      </main>
    </>
  );
}
